### ISSUE TITLE
Review & Modifications

### ISSUE THREAD

**Issue by Vignesh1115** [buildAI/aliensOnEarth#1]
We would expect you to make the code extensible so that it is easy to **plug in** a new format and the application now automatically, has the capability to export to the new format without making **any changes to the application code**.

Example - Google does not make changes to Chrome each time a new browser plugin is published. The plugin effectively provides new capability without changing any code. 

In our case consider we are adding a thousand new plugins, how feasible would the conditional statements currently being used be in that scenario.

**Comment by buildAI** [comment]
@Vignesh1115 I got the point I'm working with it. I'll fix it.

**Comment by Vignesh1115** [comment]
@buildAI Could you give us a due date on when the modified code can be expected?

**Comment by buildAI** [comment]
@Vignesh1115 hey I replied to your issue on #2 just let me know if the perception is right? I can just tell you the time once I understand the requirement.

**Comment by Vignesh1115** [comment]
1) Consider the situation where we will give you a code that returns the data to any new format. In this case lets consider the new foobar format. So effectively we are giving you the code that will create the file. We have mentioned that your application code must not be changed so I do not see a scenario where you can add a new function or replace if else. Consider that your application code is frozen from any sort of change and plan accordingly.

**Comment by buildAI** [comment]
@Vignesh1115 hey is this issue also resolved?

**Comment by Vignesh1115** [comment]
@buildAI No. We had mentioned that your application code is frozen, yet to add another format you need to make changes to dictionary.swift on #3 to assist the user in choosing the format and on #7 to recognize the function. Ideally we would like it to be detected automatically and hence make it a **plug in**.

**Comment by buildAI** [comment]
@Vignesh1115 I just made the application code modular by separating the base code to write files as a separate file. To add a new format one has to just add the format details, function name to dictionary_list.swift so we can add number of formats and add the function to file_formats.swift
